apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: fallback-api-certificate
  namespace: {{ namespace }}
spec:
  secretName: fallback-api-tls
  issuerRef:
    kind: ClusterIssuer
    name: lets-encrypt
  dnsNames:
    - {{ hostname }}