apiVersion: v1
kind: Service
metadata:
  name: fallback-api-service
  namespace: {{ namespace }}
spec:
  selector:
    app: fallback-api
    branch: {{ git_branch }}
  ports:
    - port: 8080
      name: springboot-port