version: "3.8"

services:
  fallback-api:
    image: ghcr.io/ruchira088/video-downloader-fallback-api:main
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - 8080:8080

  postgres:
    image: postgres
    command: "postgres -c log_statement=all"
    healthcheck:
      test: "pg_isready -U admin -d video-downloader-fallback-api"
      start_period: 5s
      interval: 5s
      timeout: 3s
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "video-downloader-fallback-api"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password"

  redis:
    image: redis
    command: "redis-server --requirepass redis-password"
    healthcheck:
      test: "redis-cli ping"
      start_period: "5s"
      interval: "5s"
      timeout: "3s"
    ports:
      - 6379:6379