version: "3.8"

services:
  nginx:
    image: nginx:stable-alpine
    depends_on:
      fallback-api:
        condition: service_healthy
    ports:
      - 443:443
    healthcheck:
      test: "/opt/scripts/wait-for.sh -t 3 localhost:443"
      start_period: 3s
      interval: 3s
      timeout: 2s
    volumes:
      - "./nginx/ssl:/etc/ssl"
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./docker-compose/scripts:/opt/scripts"

  fallback-api:
    image: ghcr.io/ruchira088/video-downloader-fallback-api:main
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: "/opt/scripts/wait-for-it.sh localhost:8080"
      start_period: 5s
      interval: 5s
      timeout: 3s
    ports:
      - 8080:8080
    environment:
      DATABASE_URL: "jdbc:postgresql://postgres:5432/video-downloader-fallback-api"
      DATABASE_USER: "admin"
      DATABASE_PASSWORD: "password"
    volumes:
      - "./docker-compose/scripts:/opt/scripts"

  postgres:
    image: postgres
    command: "postgres -c log_statement=all"
    healthcheck:
      test: "pg_isready -U admin -d video-downloader-fallback-api"
      start_period: 5s
      interval: 5s
      timeout: 3s
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "video-downloader-fallback-api"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password"